[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

# Set a specific, modern Python version
[build.environment]
  PYTHON_VERSION = "3.11"

# More specific configuration for our function named "api"
[functions."api"]
  included_files = ["templates/**", "static/**"]

# The redirect rule remains the same
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200