[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

[functions]
  included_files = ["app.py", "templates/**", "static/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
